version: "3.9"

services:
  backend:
    build: .
    container_name: amikiyo_backend
    command: gunicorn amikiyo_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
      - ./media:/app/media
    ports:
      - "8000:8000"
    restart: always