# Generated by Django 6.0 on 2026-02-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_postview'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('user', 'post')},
        ),
    ]
