# Generated by Django 6.0 on 2026-02-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_groupchat_groupmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending')], default='active', max_length=10),
        ),
    ]
