# Generated by Django 6.0 on 2026-02-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_groupmember_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupchat',
            options={},
        ),
        migrations.AddField(
            model_name='groupchat',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='anime_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='anime_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
