# Generated by Django 6.0 on 2026-02-23 05:53

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_groupchat_options_groupchat_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddConstraint(
            model_name='groupchat',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('is_active', True)), name='unique_active_group_name_ci'),
        ),
    ]
